// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9d_swo7iXkxaxadeSkbSPerNvcBRsMNg',
    appId: '1:183823837767:web:247fa99387a67f8c9b1f62',
    messagingSenderId: '183823837767',
    projectId: 'gymmanagementcaps',
    authDomain: 'gymmanagementcaps.firebaseapp.com',
    storageBucket: 'gymmanagementcaps.firebasestorage.app',
    measurementId: 'G-R13YTB7169',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2V8HprCahPhzShYI5LGxSSDwYHC4CcVo',
    appId: '1:183823837767:android:c364f24f3deebb649b1f62',
    messagingSenderId: '183823837767',
    projectId: 'gymmanagementcaps',
    storageBucket: 'gymmanagementcaps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiS773XcvvrikMDx00pGn47LRPrPeoSPY',
    appId: '1:183823837767:ios:fac2599dc252c5aa9b1f62',
    messagingSenderId: '183823837767',
    projectId: 'gymmanagementcaps',
    storageBucket: 'gymmanagementcaps.firebasestorage.app',
    iosBundleId: 'com.example.gymManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiS773XcvvrikMDx00pGn47LRPrPeoSPY',
    appId: '1:183823837767:ios:fac2599dc252c5aa9b1f62',
    messagingSenderId: '183823837767',
    projectId: 'gymmanagementcaps',
    storageBucket: 'gymmanagementcaps.firebasestorage.app',
    iosBundleId: 'com.example.gymManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9d_swo7iXkxaxadeSkbSPerNvcBRsMNg',
    appId: '1:183823837767:web:be08b2fa07a889ad9b1f62',
    messagingSenderId: '183823837767',
    projectId: 'gymmanagementcaps',
    authDomain: 'gymmanagementcaps.firebaseapp.com',
    storageBucket: 'gymmanagementcaps.firebasestorage.app',
    measurementId: 'G-P28Z8S62DV',
  );
}
